project:
  type: book

book:
  title: "Data-Driven Brand & Product Strategy"
  subtitle: "An R-based Analysis of YouTube and Google Trends"
  author: "**Daniel Huber & Dongyuan Gao**"
  date: "09/16/2025"
  chapters:
    - index.qmd
    - Chapters_Rbootcamp_Project/2_Prepare_the_Data_for_Analysis.qmd
    - Chapters_Rbootcamp_Project/3_Analysis_Visualisation.qmd
    - Chapters_Rbootcamp_Project/4_chapter_package_of_choice.qmd
    - Chapters_Rbootcamp_Project/5_Generative_AI.qmd
    - Chapters_Rbootcamp_Project/6_Conclusion_Limitation_Outlook.qmd
  output-file: "Data_Driven_Brand_Product_Strategy_Gao_Huber"

format:
  html:
    toc: true
    theme: flatly
    page-layout: full
    css: style.css
    fig-align: center # Center figures, titles
  pdf:
    toc: true
    number-sections: true
    documentclass: report 
    fig-align: center
    classoption: 10pt # font size adjustment(all document content)
    include-in-header:
      text: |
        \usepackage{tocloft}
        % change font size of "Table of Contents" title
        \renewcommand{\cfttoctitlefont}{\Large\bfseries}
        % adjust space above the TOC title
        \setlength{\cftbeforetoctitleskip}{-10pt} % Reduce space above
        % adjust space below the TOC title
        \setlength{\cftaftertoctitleskip}{0pt} % Space below
    geometry: top=1cm, bottom=1.5cm, left=2cm, right=2cm
    mainfont: Arial

execute:
  echo: true
  warning: false
  message: false
