project:
  type: book

book:
  title: "R Bootcamp Project"
  subtitle: "Brand and Product Strategy for Consumer Brands"
  author: "**Daniel Huber & Dongyuan Gao**"
  date: "today"
  chapters:
    - index.qmd
    - Chapters_Rbootcamp_Project/2_Prepare_the_Data_for_Analysis.qmd
    - Chapters_Rbootcamp_Project/3_Analysis_Visualisation.qmd
    - Chapters_Rbootcamp_Project/4_chapter_package_of_choice.qmd
    - Chapters_Rbootcamp_Project/5_Generative_AI.qmd
    - Chapters_Rbootcamp_Project/6_Conclusion_Limitation_Outlook.qmd

format:
  html:
    toc: true
    theme: flatly
    page-layout: full
    css: style.css
    #title-block-style: none   # disables default bootstrap card，block automatically uses .title-box
    title-block-style: default # using this to make all titles go lef
    t?
    title-block-banner: false # no banner background
  pdf:
    toc: true
    number-sections: true
    documentclass: report
    include-in-header:
      text: |
        \usepackage{titlesec}
        \titleformat{\chapter}[block]
          {\normalfont\Large\bfseries}
          {\thechapter.}
          {1em}
          {}
        % Reduce space before Table of Contents title
        \usepackage[titles]{tocloft}
        \setlength{\cftbeforetoctitleskip}{-3em}  % Adjust this value if blank space above table of content is too big
        \renewcommand{\cfttoctitlefont}{\normalfont\Large\bfseries}
    geometry: top=2.5cm, bottom=1.5cm, left=2cm, right=2cm
    mainfont: Arial

execute:
  echo: true
  warning: false
  message: false
