---
editor: 
  markdown: 
    wrap: 72
---

# Conclusion, limitations and outlook

## Conclusions

### Key Takeaways for Brands

-   **Market Positioning**: Our **proof of concept** demonstrates the rich insights 
    from Google and Youtube data for potential customers. It became clear that
    different brands play in very **different leagues**, regardless of
    their industry. Based on our analyses, we would describe the iPhone
    as a **global player**, Tesla as an **international player**, and Rolex as a
    **niche player** (although with a luxurious/international reach).
-   **Marketing Resource Allocation**: YouTube engagement around the iPhone has 
    massive spikes after **product launches** but fading quickly, while Tesla maintains 
    interest. Compared with Google, where search interest lasts several months, 
    YouTube hype is generally short-lived. This suggests our clients to allocate 
    **YouTube** marketing **immediately** after launches to catch **momentum**, 
    while deploying **Google ads** over time to **maintain** popularity.
-   **Predictive Insights & Seasonality:** We identified **correlations** 
    between different brands and created
    a **linear model** that correlates search behavior in one country
    with behavior in another. Both approaches become even more important
    when examining brands in the same industry or the response to
    multinational advertising campaigns. And we were able to demonstrate
    the **seasonality** of search behavior on Google using the example
    of Rolex. This insight is of **direct benefit** to brand managers,
    as it helps them better manage slumps or extend peaks through
    campaigns.
-   **Importance of Engagement:** Using YouTube videos, we were able to show 
    that brand managers
    should keep an eye on **user engagement**, both positive in the form
    of likes/views and negative in the form of dislikes/views, and
    compare it with that of their competitors.
-   **Content & Brand Alignment: ** Finally, the word clouds reminded us that 
    despite all the numbers
    and ratings, **content** should not be forgotten. The numbers for
    Rolex YouTube videos may look good. But is it also in the interest
    of brand managers if the primary focus is on showcasing German
    hip-hop artists?

### Key takeaways for R-Bootcamp Learning

We implemented many different concepts and practices that we learned in the R
bootcamp and also explored **new additional topics**. For
example, we learned how to access current Google search data and how to
analyze the content of YouTube videos using wordclouds. By solving
problems using the usual R tools, Google searches, and AI chatbots, we
have now built **confidence** that we can tackle future
data science challenges.

## Limitations

Many limitations ultimately proved to be solvable problems that we were
able to fix with a little data wrangling, for example. However, some
aspects **fundamentally limited** our evaluations:

-   **Outdated YouTube Data:** We worked with a Kaggle dataset **from 2017 to 2018**.
    This was sufficient for our purposes. In addition to this use case,
    which focuses on what can be gained from YouTube data, we would of
    course also like to investigate specific cases. To do this, access
    to current data is essential.
-   **Changing Video IDs:** A second limitation arose when we attempted to track 
    certain videos over a longer period of time to see how long they remained
    available. Apparently, the **cryptic video IDs change** from time to
    time, so we were unable to perform any meaningful analysis in this
    regard.
-   **Google Trends API Restrictions:** We worked with data that we were able to 
    download daily from Google Search Trends. One initial difficulty is that
    **Google restricts downloads** in a rather unpredictable manner.
    This significantly limits the workflow, as all downloads must be
    cached locally for security reasons.
-   **Relative Google Trends Data:** However, the bigger problem with Google Search 
    is that **only relative numbers** are available. It is not possible to obtain the
    absolute number of searches per keyword. All values are calibrated
    by Google Search Trends to 0-100 for each search query. On the one
    hand, this means **a significant loss of information** and makes it
    **impossible to compare different search queries** with each other.
-   **Project Scope: ** A final limiting factor was our somewhat 
    **theoretical experimental setup**. With a more concrete case, our analysis 
    would have been much more concise and the overall picture more coherent. The fact
    that we had data from 2017/2018 and were working with such data for
    the first time prompted us to examine somewhat more general
    questions, which we considered appropriate. But let's imagine
    Guiness Beers was our client and we could observe the launch of
    their first **non-alcoholic** Guinness Stout beer! That would, of
    course, give the analysis and the story a whole different dynamic!

## Outlook

The limitations mentioned above lead to the main points we would address
next:

-   **Update to current data:** It is possible to **load current YouTube data**. 
    However, this requires a Google Cloud project and an API key. Even then, there are
    certain limitations, but the data would definitely be more
    comprehensive than the data available to us in the `Kaggle` dataset.
    In this context, we would look at the `Tuber package` (CRAN),
    which can be used to load data on specific videos. For example, if
    Rolex decides to make its own videos available on YouTube to
    influence their brand image in its favor. 
-   **Explore Google Search Metrics:** We would also try to find a way to obtain 
    **uncalibrated Google search data**. While initial attempts were proven 
    challenging as Google intentionally limit our access to this data, the
    `Google Ads Keyword Planner` could be an alternative for future attempts.
-   **Advanced Visualization:** A final area of improvement is regarding a 
    small problem for the wordclouds. It would have been nice to create the 
    iPhone word cloud in the **format of the Apple logo**.
    However, even after an intensive search, we were unable to do this.
    We will not give up and will make a few more attempts.